name: Random Wednesday Peak Commits

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "Nasvyni"
          git config --global user.email "bundo.maria@gmail.com"

      - name: Sync latest changes
        run: git pull origin main --rebase

      - name: Run Script
        run: python generate.py

      - name: Push Commits
        run: git push origin main
