name: Random Wednesday Peak Commits

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git
        run: |
          subprocess.run(["git", "config", "user.name", "Nasvyni"])
          subprocess.run(["git", "config", "user.email", "bundo.maria@gmail.com"])
      - name: Sync latest changes
        run: git pull origin main --rebase
      - name: Run Script
        run: python generate.py
      - name: Push Commits
        run: git push origin main
